# Generated by Django 5.2.3 on 2025-10-06 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('directions', '0001_initial'),
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Branch name')),
                ('description', models.TextField(verbose_name='Branch description')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='applications.application')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='BranchDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_directions', to='branch.branch')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_directions', to='directions.direction')),
            ],
            options={
                'verbose_name': 'Branch Direction',
                'verbose_name_plural': 'Branch Directions',
            },
        ),
        migrations.CreateModel(
            name='BranchEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('branch_direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_equipments', to='branch.branchdirection')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_equipments', to='equipments.equipment')),
            ],
            options={
                'verbose_name': 'Branch equipment',
                'verbose_name_plural': 'Branch equipments',
            },
        ),
        migrations.CreateModel(
            name='BranchUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('branch_direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_users', to='branch.branchdirection')),
            ],
            options={
                'verbose_name': 'Branch User',
                'verbose_name_plural': 'Branch Users',
            },
        ),
    ]
