# Generated by Django 5.2.3 on 2025-10-06 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branchuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='branchdirection',
            unique_together={('branch', 'direction')},
        ),
        migrations.AlterUniqueTogether(
            name='branchequipment',
            unique_together={('branch_direction', 'equipment')},
        ),
        migrations.AlterUniqueTogether(
            name='branchuser',
            unique_together={('branch_direction', 'user')},
        ),
    ]
