# Generated by Django 5.2.3 on 2025-10-07 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_initial'),
        ('users', '0002_remove_employee_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_users', to='users.employee'),
        ),
    ]
