# Generated by Django 5.2.3 on 2025-10-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Registration number'),
        ),
    ]
